import Head from 'next/head';
import Filter from '../components/Filter';
import Header from '../components/Header';
import { Rides } from '../components/Rides';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Edvora Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Filter />

      <Rides />

      <footer className="w-full h-[10vh]"></footer>
    </div>
  );
}
